import { Inter } from "next/font/google";
import "./globals.css";
// import Drawer from "@/components/shared/Drawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* <Drawer/> */}
        {children}
        
        </body>
    </html>
  );
}
